# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
      - id: eslint
        args:
          [
            --fix,
            --report-unused-disable-directives,
            --config,
            server/.eslintrc.yaml,
          ]
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        verbose: true
        additional_dependencies:
          - eslint@8.15.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-jest@26.1.5
          - eslint-plugin-react@6.10.3
          - eslint-import-resolver-typescript@2.2.1
          - '@typescript-eslint/eslint-plugin@5.23.0'
          - '@typescript-eslint/parser@5.23.0'
          - eslint-config-airbnb-base@15.0.0
          - prettier@2.0.5
          - eslint-plugin-prettier@4.0.0
          - eslint-config-prettier@8.5.0
