---
root: true
env:
  es2020: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:prettier/recommended # This comes last
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
  - "@typescript-eslint"
  - jest
rules:
  no-underscore-dangle: off
  class-methods-use-this: off
  camelcase: off
  prettier/prettier: error
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
  - error
  - varsIgnorePattern: ^_
    argsIgnorePattern: ^_
    destructuredArrayIgnorePattern: ^_
    ignoreRestSiblings: true
    "@typescript-eslint/naming-convention":
    - error
    - format:
        - "camelCase"
        - "PascalCase"
        - "UPPER_CASE"
      selector: "default"
      leadingUnderscore: allow
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/*.test.js"
        - "**/*.test.ts"
        - "**/*.spec.js"
        - "**/*.spec.ts"
  import/extensions:
    - error
    - ignorePackages
    - ts: never
      tsx: never
  no-console: off
settings:
  import/resolver:
    typescript:
