name: Running Code Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: server/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
