---
root: true
env:
  es2020: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended # This comes last
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
  - '@typescript-eslint'
  - react
  - react-hooks
  - jest
rules:
  class-methods-use-this:
    - 'off'
  camelcase: 'off'
  prettier/prettier: error
  import/extensions:
    - error
    - ignorePackages
    - ts: never
      tsx: never
  no-console:
    - 'off'
settings:
  import/resolver:
    typescript:
  react:
    version: detect
