---
root: true
env:
  es2020: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:prettier/recommended # This comes last
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
  - '@typescript-eslint'
  - jest
rules:
  prettier/prettier: error
  import/extensions:
    - error
    - ignorePackages
    - ts: never
  no-console:
    - 'off'
settings:
  import/resolver:
    typescript:
# FIXME[id=eslint-note] - This file can't be extended without causing include errors. ESLint thinks it should import relative to this file instead of the one that is importing it -- what would be ideal for the project. In the meantime, we'll just have to live with copying this garbage to the other projects. Go ahead and hardlink them if you're making changes. `ln -f .eslintrc.base.yaml server/.eslintrc.base.yaml`. It's also renamed to ESLint not try to use this
